'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PAQCompress.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to v0.3.14
        '''-Targets .NET Framework 4.8
        '''-Added paq8px_v179fix5
        '''
        '''v0.3.13
        '''-Added paq8px_v179fix4
        '''-Enabled the &quot;Clear Log&quot; button to erase log while compression/extraction is in progress.
        '''
        '''v0.3.12
        '''-Added paq8px_v179fix3
        '''
        '''v0.3.11
        '''-Added paq8px_v179fix2
        '''
        '''v0.3.10
        '''-Added paq8px_v179 and paq8px_v179fix1.
        '''-Added paq8px_v147 which was missing from the list.
        '''
        '''v0.3.9
        '''-Fixed OpenFileDialog message saying &quot;Browse for a file to compress&quot; when the Extract Radiobutton was checked.
        '''
        '''v0.3.8
        '''-Added paq8pxv_v8 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Changelog() As String
            Get
                Return ResourceManager.GetString("Changelog", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
